name: atlite-era5-land
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - affine=2.4.0
  - asttokens=3.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.3
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - branca=0.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - capnproto=1.2.0
  - cartopy=0.25.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - cfgrib=0.9.15.1
  - cfitsio=4.6.2
  - cftime=1.6.4
  - charset-normalizer=3.4.4
  - click=8.3.0
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cycler=0.12.1
  - cytoolz=1.1.0
  - dask=2025.10.0
  - dask-core=2025.10.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.10.0
  - double-conversion=3.3.1
  - eccodes=2.44.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - findlibs=0.1.2
  - fmt=11.2.0
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - freexl=2.0.0
  - fsspec=2025.9.0
  - gdal=3.10.3
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.14.0
  - geotiff=1.7.4
  - graphite2=1.3.14
  - h2=4.3.0
  - h5netcdf=1.7.3
  - h5py=3.15.1
  - harfbuzz=12.1.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=8.37.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_pygments=0.3.0
  - kealib=1.6.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.2
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=21.1.4
  - libcrc32c=1.1.2
  - libcurl=8.16.0
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal=3.10.3
  - libgdal-core=3.10.3
  - libgdal-fits=3.10.3
  - libgdal-grib=3.10.3
  - libgdal-hdf4=3.10.3
  - libgdal-hdf5=3.10.3
  - libgdal-jp2openjpeg=3.10.3
  - libgdal-kea=3.10.3
  - libgdal-netcdf=3.10.3
  - libgdal-pdf=3.10.3
  - libgdal-pg=3.10.3
  - libgdal-postgisraster=3.10.3
  - libgdal-tiledb=3.10.3
  - libgdal-xls=3.10.3
  - libglib=2.86.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnetcdf=4.9.3
  - libparquet=21.0.0
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.0
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - locket=1.0.0
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - minizip=4.0.10
  - mistune=3.1.4
  - mkl=2024.2.2
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - narwhals=2.9.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.7.3
  - networkx=3.4.2
  - numpy=2.2.6
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.46
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - poppler=25.07.0
  - poppler-data=0.4.12
  - postgresql=17.6
  - proj=9.6.2
  - prompt-toolkit=3.0.52
  - psutil=7.1.1
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyogrio=0.11.0
  - pyparsing=3.2.5
  - pyproj=3.7.1
  - pyshp=3.0.2
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-eccodes=2.44.0
  - python-fastjsonschema=2.21.2
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - rasterio=1.4.3
  - re2=2025.08.12
  - referencing=0.37.0
  - requests=2.32.5
  - rioxarray=0.19.0
  - rpds-py=0.30.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - setuptools=80.9.0
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - spdlog=1.15.3
  - sqlite=3.50.4
  - stack_data=0.6.3
  - tbb=2021.13.0
  - tblib=3.1.0
  - threadpoolctl=3.6.0
  - tiledb=2.28.1
  - tinycss2=1.5.1
  - tk=8.6.13
  - toolz=1.1.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xarray=2025.6.1
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - atlite==0.4.1.post1.dev9+gf97896b3a.d20260113
      - bottleneck==1.6.0
      - cdsapi==0.7.7
      - ecmwf-datastores-client==0.4.0
      - multiurl==0.3.7
      - numexpr==2.14.1
      - progressbar2==4.5.0
      - python-utils==3.9.1
prefix: C:\Users\gohng\.conda\envs\atlite_clean
